version: "3.7"

x-homelinksink-defaults: &homelinksink-defaults
  restart: unless-stopped
  image: homelinkstash:latest
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

services:
  homelink-stash:
    <<: *homelinksink-defaults
    container_name: homelink-stash
    network_mode: host
    volumes:
      - "./settings.json:/usr/src/service/dist/settings/settings.json"