version: "3.7"

x-homelinksink-defaults: &homelinksink-defaults
  restart: unless-stopped
  image: homelinksink:latest
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

services:
  homelink-stash:
    <<: *homelinksink-defaults
    container_name: homelink-stash
    network_mode: host
    volumes:
      - "./src/env:/etc/homelink-stash/env"
    environment:
      - NODE_ENV=local
